version: '3.4'

services:
  authorization.api:
    image: authorization:1.0.0
    build:
      context: Authorization
      dockerfile: Authorization.API/Dockerfile
      args:
        PAT: ${PAT}
  
  email.worker:
    image: email:1.0.0
    build:
      context: Email
      dockerfile: Email.Worker/Dockerfile
      args:
        PAT: ${PAT}

  management.graphql:
    image: management:1.0.0
    build:
      context: Management
      dockerfile: Management.GraphQL/Dockerfile
      args:
        PAT: ${PAT}

  website.blazor:
    image: website:1.0.0
    build:
      context: Website
      dockerfile: Website.Blazor/Dockerfile
      args:
        PAT: ${PAT}