version: '3.4'

services:
  authorization.api:
    image: authorization:latest
    build:
      context: Authorization
      dockerfile: Authorization.API/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_URLS=http://*:5001/
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthorizationDB=${HostConnectionStrings_Authorization}
      - KafkaOptions__BootstrapServers=kafka:29092
    ports:
      - "5001:5001"
  
  email.worker:
    image: email:latest
    build:
      context: Email
      dockerfile: Email.Worker/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KafkaOptions__BootstrapServers=kafka:29092

  management.graphql:
    image: management:latest
    build:
      context: Management
      dockerfile: Management.GraphQL/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_URLS=http://*:5002/
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ManagementDB=${HostConnectionStrings_Management}
      - KafkaOptions__BootstrapServers=kafka:29092
    ports:
      - "5002:5002"

  website.blazor:
    image: website:latest
    build:
      context: Website
      dockerfile: Website.Blazor/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_URLS=http://*:5003/
      - ASPNETCORE_ENVIRONMENT=Development
      - KafkaOptions__BootstrapServers=kafka:29092
    ports:
      - "5003:5003"

  ### Kafka related
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1