version: '3.4'

services:
  authorization.api:
    image: authorization:latest
    build:
      context: Authorization
      dockerfile: Authorization.API/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_URLS=http://*:5001/
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthorizationDB=${HostConnectionStrings_Authorization}
    ports:
      - "5001:5001"
  
  email.worker:
    image: email:latest
    build:
      context: Email
      dockerfile: Email.Worker/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  management.graphql:
    image: management:latest
    build:
      context: Management
      dockerfile: Management.GraphQL/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_URLS=http://*:5002/
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ManagementDB=${HostConnectionStrings_Management}
    ports:
      - "5002:5002"

  website.blazor:
    image: website:latest
    build:
      context: Website
      dockerfile: Website.Blazor/Dockerfile
      args:
        PAT: ${PAT}
    environment:
      - ASPNETCORE_URLS=http://*:5003/
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:5003"