apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ToBeReplaced.com
    http:
      paths:
      {{- range .Values.ingressEndpoint }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .serviceName }}
            port:
              number: {{ .port }}
      {{- end }}