apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "donotuseme" .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.applicationName }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
          - name: JAEGER_SERVICE_NAME
            value: {{ .Values.applicationName }}
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | default "" | quote }}
          {{- end }}
          {{- range $key, $value := .Values.global.env }}
          - name: {{ $key | quote }}
            value: {{ $value | default "" | quote }}
          {{- end }}
          {{- if .Values.secrets }}
          {{- toYaml .Values.secrets | nindent 10 }}
          {{- end }}
    {{- if .Values.global.imagePullSecret }}  
      imagePullSecrets: 
        - name: {{ .Values.global.imagePullSecret }}
    {{- end }}